name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: latest

      - name: Install dependencies  
        run: npm install

      - name: Build
        run: npm run build
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app-build-artifacts
          path: dist/**/*

